sudo: required
services:
    -docker

before_install:
    - docker build -t sambhaba/dockerdevandprod -f Dockerfile.dev .  

script:
    - docker run -e CI=true sambhaba/dockerdevandprod npm run test -- --coverage


deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockerdevandprod"
    env: "dockerdevandprod-env"
    bucket_name: "elasticbeanstalk-us-east-2-141043694641"
    bucket_path:  "dockerdevandprod"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"


        
